name: compass
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_vibrate: ^1.3.0
  intl: ^0.18.0
  sensors_plus: ^4.0.1
  wear: ^1.1.0
  wearable_rotary: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
     - assets/line_background.png
     - assets/dial.png

  generate: true
